[package]
name = "infinitier_core"
version.workspace = true
edition.workspace = true

[dependencies]
encoding_rs =  { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
